import { PrismaClient } from "@prisma/client"
import { PrismaPg } from "@prisma/adapter-pg"
import { config } from "dotenv"

config({ path: ".env.local" })

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! })
const prisma = new PrismaClient({ adapter })

// Image pool by destination
const IMG = {
  serengeti: (n: number) => `/images/destinations/serengeti/serengeti-${n}.webp`,
  ngorongoro: (n: number) => `/images/destinations/ngorongoro/ngorongoro-${n}.webp`,
  tarangire: (n: number) => `/images/destinations/tarangire/tarangire-${n}.webp`,
  arusha: (n: number) => `/images/destinations/arusha/arusha-${n}.webp`,
  kilimanjaro: (n: number) => `/images/destinations/kilimanjaro/kilimanjaro-${n}.webp`,
  manyara: (n: number) => `/images/destinations/lake-manyara/lake-manyara-${n}.webp`,
  migration: (n: number) => `/images/destinations/migration/migration-${n}.webp`,
  ruaha: "/images/destinations/ruaha/Ruaha-NP-1900x1000-1.webp",
  ruaha2: "/images/destinations/ruaha/Ruaha-elephants-1-1900x640-1.webp",
  nyerere: "/images/destinations/nyerere/Selous-giraffe-river-reflections-RR.webp",
  zanzibar: (n: number) => `/images/destinations/zanzibar/zanzibar-${n}.webp`,
}

// ─── CAMPS ─────────────────────────────────────────────────────────────────
const CAMPS = [
  // ── Already seeded (skip if exists) ─────────────────────────────────────
  // serenity-camp-lodges, serenity-great-migration-camp, serenity-mara-river-camp,
  // serenity-nyerere-bush-camp, serenity-zanzibar-beachfront (handled below)

  // ── Serengeti Luxury Camps ───────────────────────────────────────────────
  {
    name: "Namiri Plains",
    slug: "namiri-plains",
    status: "PUBLISHED" as const,
    type: "Luxury Tented Camp",
    destination: "Eastern Serengeti",
    description: "Exuding style and exclusivity deep in Tanzania's eastern Serengeti, Namiri Plains occupies one of the most exclusive game-viewing zones in the park — renowned as big cat country. Resident cheetahs, lions and leopards roam the open plains surrounding camp, delivering front-row wildlife encounters from your private tent veranda morning and evening.",
    highlights: ["Exclusive big cat territory", "Private plunge pools", "Eastern Serengeti seclusion", "Resident cheetah populations", "Expert naturalist guides", "Star bed experiences"],
    amenities: ["Private plunge pools", "Open-air lounge & bar", "Swimming pool", "Sundowner setups", "Guided walking safaris", "Night game drives", "Campfire evenings", "En-suite bathrooms"],
    priceFrom: 1100,
    coverImage: IMG.serengeti(5),
    gallery: [IMG.serengeti(5), IMG.serengeti(12), IMG.serengeti(20)],
    website: "",
  },
  {
    name: "Sayari Camp",
    slug: "sayari-camp",
    status: "PUBLISHED" as const,
    type: "Luxury Tented Camp",
    destination: "Northern Serengeti",
    description: "Holding prime position near the Mara River in Tanzania's remote northern Serengeti, Sayari Camp blends stylish elegance with an authentic bush atmosphere. Leather sofas, a stone fireplace, and a shimmering swimming pool set the scene for a safari season marked by dramatic Mara River crossings and year-round big cat activity in one of Africa's most coveted wildlife corridors.",
    highlights: ["Mara River crossing access", "Leather lounge & stone fireplace", "Swimming pool", "Northern Serengeti exclusivity", "Year-round big cats", "Photographic specialist guides"],
    amenities: ["Swimming pool", "Lounge bar", "Stone fireplace", "Private verandas", "Walking safaris", "Bush breakfast setup", "Night game drives", "Laundry service"],
    priceFrom: 1050,
    coverImage: IMG.serengeti(8),
    gallery: [IMG.serengeti(8), IMG.serengeti(15), IMG.serengeti(22)],
    website: "",
  },
  {
    name: "Olakira Migration Camp",
    slug: "olakira-migration-camp",
    status: "PUBLISHED" as const,
    type: "Mobile Camp",
    destination: "Serengeti Ecosystem",
    description: "Serenity's most dynamic camp experience — Olakira follows the Great Migration across the Serengeti calendar, repositioning between river crossings and calving season for the ultimate front-row wildlife theatre. Classic canvas tents, an outdoor bar and bush dining setups under the stars make this the perfect mobile safari for guests who want to be exactly where the action is.",
    highlights: ["Follows Great Migration year-round", "River crossing season prime position", "Calving season on southern plains", "Classic canvas tents", "Intimate 8-guest capacity", "Full-service mobile operation"],
    amenities: ["En-suite flush bathrooms", "Hot bucket showers", "Gourmet bush kitchen", "Open bar", "Campfire evenings", "Pre-dawn game drives", "Bush sundowners", "Private guide available"],
    priceFrom: 850,
    coverImage: IMG.migration(3),
    gallery: [IMG.migration(3), IMG.migration(7), IMG.migration(11)],
    website: "",
  },
  {
    name: "Ubuntu Migration Camp",
    slug: "ubuntu-migration-camp",
    status: "PUBLISHED" as const,
    type: "Mobile Camp",
    destination: "Serengeti Ecosystem",
    description: "Ubuntu moves between two strategically chosen Serengeti locations delivering intimate Great Migration experiences in a warm, community-spirited atmosphere. An open-sided dining tent, central lounge, campfire and canvas accommodations create a classically authentic safari rhythm — connecting guests deeply with the land, wildlife, and the timeless pulse of the Serengeti.",
    highlights: ["Two seasonal Serengeti locations", "Intimate migration experience", "Open-sided dining tent", "Community-led conservation", "Classic campfire atmosphere", "Dawn game drive priority"],
    amenities: ["Open-sided dining & lounge", "Central campfire", "En-suite tents", "Hot showers", "Bush breakfast setups", "Migration expert guides", "Sundowner vehicle stops", "In-tent butler service"],
    priceFrom: 800,
    coverImage: IMG.migration(5),
    gallery: [IMG.migration(5), IMG.migration(9), IMG.migration(13)],
    website: "",
  },
  {
    name: "Dunia Camp",
    slug: "dunia-camp",
    status: "PUBLISHED" as const,
    type: "Luxury Tented Camp",
    destination: "Central Serengeti",
    description: "Strategically positioned in the south-central Serengeti, Dunia Camp provides exceptional year-round game viewing in the core of Tanzania's most celebrated wildlife zone. Resident prides of lion, large elephant herds and the full cast of plains game are daily sightings, while the camp's warm, intimate atmosphere makes every guest feel personally attended to.",
    highlights: ["Year-round game viewing", "Core Serengeti location", "Resident lion prides", "Experienced female-led team", "Intimate 8-tent camp", "Walking safari specialists"],
    amenities: ["Guest tents with verandas", "Campfire area", "Bar & lounge", "Pool", "Walking safaris", "Specialist birding walks", "Bush dining", "Laundry included"],
    priceFrom: 900,
    coverImage: IMG.serengeti(18),
    gallery: [IMG.serengeti(18), IMG.serengeti(25), IMG.serengeti(30)],
    website: "",
  },
  {
    name: "The Highlands",
    slug: "the-highlands-ngorongoro",
    status: "PUBLISHED" as const,
    type: "Luxury Tented Camp",
    destination: "Ngorongoro Conservation Area",
    description: "The Highlands redefines the Ngorongoro experience, offering an immersive highland adventure woven from wildlife, culture, and exploration. Perched on the misty moorlands above the crater, each domed tent commands sweeping panoramas over ancient caldera walls. Walking trails through Afro-alpine landscapes and crater descents for Big Five encounters make this one of East Africa's most distinctive safari camps.",
    highlights: ["Ngorongoro crater panoramas", "Afro-alpine walking trails", "Big Five including black rhino", "Cultural Maasai interactions", "Domed tent architecture", "Crater rim exclusivity"],
    amenities: ["Family rooms with children's beds", "Lounge & bar", "Crater descent game drives", "Walking safaris", "Maasai guide partnerships", "Heated tents", "Private viewing decks", "Stargazing kits"],
    priceFrom: 950,
    coverImage: IMG.ngorongoro(3),
    gallery: [IMG.ngorongoro(3), IMG.ngorongoro(7), IMG.ngorongoro(11)],
    website: "",
  },
  {
    name: "Oliver's Camp",
    slug: "olivers-camp-tarangire",
    status: "PUBLISHED" as const,
    type: "Luxury Tented Camp",
    destination: "Tarangire National Park",
    description: "Offering an exclusive and authentically wild experience in southern Tarangire, Oliver's Camp is celebrated for having some of Tanzania's most accomplished and knowledgeable guides. Set in a remote sector accessed by few visitors, the camp delivers extraordinary game density, ancient elephant bulls, walking safaris of the highest calibre, and an atmosphere of genuine bush immersion.",
    highlights: ["Remote southern Tarangire sector", "Expert specialist guides", "Elephant bulls & large herds", "Infinity pool with bush views", "Walking safari specialists", "Exclusive game-viewing area"],
    amenities: ["Luxury safari tents", "Infinity pool", "Campfire lounge", "Lantern-lit dining", "Walking safaris", "Night drives", "Birding specialists", "Butler service"],
    priceFrom: 980,
    coverImage: IMG.tarangire(5),
    gallery: [IMG.tarangire(5), IMG.tarangire(12), IMG.tarangire(19)],
    website: "",
  },
  {
    name: "Usangu Expedition Camp",
    slug: "usangu-expedition-camp",
    status: "PUBLISHED" as const,
    type: "Fly Camp",
    destination: "Ruaha Ecosystem",
    description: "Deep in the remote Usangu Wetlands at the source of the Great Ruaha River, this expedition camp offers a conservation-driven journey into one of Tanzania's last unexplored wilderness frontiers. Raised platform tents, observation decks with telescopes, and expert naturalist guides open a world rarely witnessed — vast floodplains alive with birds, buffalo herds and undisturbed wildlife.",
    highlights: ["Remote Usangu Wetlands", "Conservation research access", "Raised platform tents", "Telescope observation decks", "Pristine unexplored wilderness", "Specialist ornithology guides"],
    amenities: ["Raised platform tents", "Observation decks with telescopes", "Research station access", "Bush meals", "Walking safaris", "Boat excursions in wet season", "Solar power", "Conservation briefings"],
    priceFrom: 720,
    coverImage: IMG.ruaha,
    gallery: [IMG.ruaha, IMG.ruaha2],
    website: "",
  },
  {
    name: "Rubondo Island Camp",
    slug: "rubondo-island-camp",
    status: "PUBLISHED" as const,
    type: "Luxury Tented Camp",
    destination: "Lake Victoria",
    description: "On a forested island sanctuary in Lake Victoria, Rubondo Island Camp offers one of Tanzania's most unique and exclusive wildlife adventures. Home to habituated chimpanzees, forest elephants, sitatunga antelope and over 300 bird species, this remote island delivers intimate encounters impossible anywhere else. Lakeside fire gatherings, chimp trekking and exceptional fishing complete the experience.",
    highlights: ["Chimpanzee trekking", "Forest elephants", "Lake Victoria island setting", "Over 300 bird species", "Sitatunga antelope", "Exclusive remote access"],
    amenities: ["Island tented accommodations", "Lakeside campfire", "Chimp trekking permits", "Fishing safaris", "Bird walks", "Canoe excursions", "Boat transfers", "Full board"],
    priceFrom: 880,
    coverImage: IMG.serengeti(35),
    gallery: [IMG.serengeti(35), IMG.serengeti(40)],
    website: "",
  },
  {
    name: "Kisima Ngeda Tented Camp",
    slug: "kisima-ngeda-tented-camp",
    status: "PUBLISHED" as const,
    type: "Permanent Tented Camp",
    destination: "Lake Eyasi",
    description: "On the shores of ancient Lake Eyasi in the Great Rift Valley, Kisima Ngeda offers a deeply cultural and wildlife-rich retreat unlike any other in Tanzania. Exceptional birding, exclusive Hadzabe bushman interactions, and the raw, otherworldly landscape of the soda lake create a safari experience that broadens the definition of the wild.",
    highlights: ["Lake Eyasi shoreline", "Hadzabe cultural walks", "Over 200 bird species", "Datoga blacksmith visits", "Great Rift Valley views", "Remote & intimate"],
    amenities: ["Lakeside tented rooms", "Veranda dining", "Cultural guide partnerships", "Fishing on Lake Eyasi", "Birding specialist walks", "Sundowner boat trips", "Solar power", "Local cuisine"],
    priceFrom: 580,
    coverImage: IMG.manyara(6),
    gallery: [IMG.manyara(6), IMG.manyara(10)],
    website: "",
  },
  {
    name: "Lake Masek Tented Lodge",
    slug: "lake-masek-tented-lodge",
    status: "PUBLISHED" as const,
    type: "Permanent Tented Camp",
    destination: "Ndutu, Southern Serengeti",
    description: "Nestled on the shores of Lake Masek at the edge of the Ndutu woodland, this tented lodge occupies a prime position for the calving season when hundreds of thousands of wildebeest birth their young on the southern Serengeti plains. Flamingos on the lake, lion hunts at dawn and the raw drama of new life make this one of Tanzania's most emotionally powerful safari experiences.",
    highlights: ["Prime calving season location", "Lake Masek flamingos", "Ndutu woodland setting", "Lion & cheetah activity", "Wildebeest calving front row", "Beautiful seasonal landscapes"],
    amenities: ["Lakeside tented rooms", "Bar & lounge", "Game drives at calving", "Walking safaris", "Bush breakfasts", "Sunset lake views", "Generator & solar power", "Airport transfers"],
    priceFrom: 650,
    coverImage: IMG.migration(2),
    gallery: [IMG.migration(2), IMG.migration(6), IMG.migration(10)],
    website: "",
  },
  {
    name: "Lemala Ndutu Camp",
    slug: "lemala-ndutu-camp",
    status: "PUBLISHED" as const,
    type: "Luxury Tented Camp",
    destination: "Ndutu, Southern Serengeti",
    description: "Lemala Ndutu Camp delivers a luxurious calving season experience in the heart of Tanzania's most dramatic wildlife spectacle. Positioned deep in the Ndutu woodlands, the camp's intimate tented suites and expert guides ensure guests experience the wildebeest calving phenomenon with proximity, comfort and insight that transforms a holiday into a life-defining memory.",
    highlights: ["Premium calving season camp", "Ndutu core area access", "Intimate luxury tents", "Expert guides", "Cheetah & big cat tracking", "Early morning priority game drives"],
    amenities: ["Luxury suite tents", "Private verandas", "Swimming pool", "Gourmet dining", "Expert guides", "Pre-dawn game drives", "Bush dining setups", "Spa treatments on request"],
    priceFrom: 900,
    coverImage: IMG.migration(4),
    gallery: [IMG.migration(4), IMG.migration(8), IMG.migration(12)],
    website: "",
  },
  {
    name: "Kati Kati Tented Camp",
    slug: "kati-kati-tented-camp",
    status: "PUBLISHED" as const,
    type: "Permanent Tented Camp",
    destination: "Serengeti National Park",
    description: "A classic East African tented camp experience in the heart of the Serengeti, Kati Kati offers genuine safari immersion at an accessible price. Comfortable canvas tents, warm communal areas and knowledgeable guides deliver memorable game drives across one of the world's greatest wildlife stages — bringing the Serengeti dream within reach for every style of traveller.",
    highlights: ["Classic East African atmosphere", "Central Serengeti location", "Accessible luxury", "Knowledgeable local guides", "Night game drives", "Full-service safari experience"],
    amenities: ["Canvas tents with beds", "Communal dining tent", "Bar & lounge", "Game drives", "Walking safaris", "Campfire evenings", "Shared facilities", "Full board"],
    priceFrom: 420,
    coverImage: IMG.serengeti(42),
    gallery: [IMG.serengeti(42), IMG.serengeti(48)],
    website: "",
  },
  {
    name: "Kubu Kubu Tented Lodge",
    slug: "kubu-kubu-tented-lodge",
    status: "PUBLISHED" as const,
    type: "Permanent Tented Camp",
    destination: "Central Serengeti",
    description: "Kubu Kubu Tented Lodge occupies a rocky kopje in the central Serengeti, offering iconic views across the golden plains and consistent year-round wildlife action. Its elevated position provides natural vantage points for spotting predators and large herds, while the warm atmosphere and attentive service create a comfortable base for exploring Africa's most celebrated national park.",
    highlights: ["Rocky kopje elevation", "Year-round game viewing", "Panoramic plains views", "Predator tracking specialists", "Central park location", "Warm family atmosphere"],
    amenities: ["Tented rooms", "Rock kopje lounge", "Bar & pool", "Game drives", "Walking safaris", "Bush meals", "Laundry service", "Airport transfers"],
    priceFrom: 560,
    coverImage: IMG.serengeti(50),
    gallery: [IMG.serengeti(50), IMG.serengeti(55)],
    website: "",
  },
]

// ─── LODGES ────────────────────────────────────────────────────────────────
const LODGES = [
  // ── Already seeded (skip if exists) ─────────────────────────────────────
  // serenity-camp-lodges, serenity-ngorongoro-highlands,
  // serenity-ruaha-river, serenity-tarangire-palm

  // ── Ruaha ────────────────────────────────────────────────────────────────
  {
    name: "Jabali Ridge",
    slug: "jabali-ridge-ruaha",
    status: "PUBLISHED" as const,
    type: "Luxury Lodge",
    destination: "Ruaha National Park",
    description: "Perched on a dramatic rocky ridge above Tanzania's largest national park, Jabali Ridge is a sophisticated lodge that provides an unrivalled base for exploring Ruaha's vast wilderness by vehicle and on foot. Elegant stone-and-timber suites with private decks, an open-air lounge, curated cocktail bar and a fire pit beneath the stars define a standard of comfort that elevates every game drive.",
    highlights: ["Ridge-top panoramic views", "Stone suites with private decks", "Walking safari specialists", "Fire pit & evening lounge", "Vast & exclusive wilderness", "Wild dog & lion territory"],
    amenities: ["Stone suites with decks", "Open-air lounge & bar", "Fire pit", "Swimming pool", "Walking safaris", "Night game drives", "Fine dining restaurant", "Spa room"],
    priceFrom: 1100,
    coverImage: IMG.ruaha,
    gallery: [IMG.ruaha, IMG.ruaha2],
    website: "",
  },

  // ── Arusha City ──────────────────────────────────────────────────────────
  {
    name: "Gran Meliá Arusha",
    slug: "gran-melia-arusha",
    status: "PUBLISHED" as const,
    type: "Luxury Lodge",
    destination: "Arusha",
    description: "Tanzania's most prestigious city hotel, Gran Meliá Arusha sets the standard for urban luxury with sweeping views of Mount Meru from its manicured gardens and rooftop terrace. The ideal gateway lodge before or after a safari, combining world-class dining, a full spa, and the sophistication of an international luxury brand with Tanzania's warm sense of welcome.",
    highlights: ["Mount Meru views", "Rooftop restaurant & bar", "Full spa & wellness", "International luxury brand", "Safari gateway location", "Conference facilities"],
    amenities: ["Luxury rooms & suites", "Full spa", "Outdoor pool", "Multiple restaurants", "Rooftop terrace bar", "Fitness centre", "Business centre", "Airport transfers"],
    priceFrom: 480,
    coverImage: IMG.arusha(3),
    gallery: [IMG.arusha(3), IMG.arusha(8), IMG.arusha(13)],
    website: "",
  },
  {
    name: "Four Points by Sheraton Arusha",
    slug: "four-points-sheraton-arusha",
    status: "PUBLISHED" as const,
    type: "Standard Lodge",
    destination: "Arusha",
    description: "A reliable and comfortable city base in the heart of Arusha, Four Points by Sheraton offers the consistency of an international chain with warm Tanzanian hospitality. Well-appointed rooms, a swimming pool, and convenient proximity to Arusha's safari departure hubs make this the practical choice for pre- and post-safari nights.",
    highlights: ["Central Arusha location", "International standard comfort", "Swimming pool", "Easy safari hub access", "Reliable service standards", "Good value"],
    amenities: ["Standard rooms", "Swimming pool", "Restaurant & bar", "Fitness centre", "Free WiFi", "Airport transfers", "Tour desk", "24h room service"],
    priceFrom: 180,
    coverImage: IMG.arusha(5),
    gallery: [IMG.arusha(5), IMG.arusha(10)],
    website: "",
  },
  {
    name: "Mount Meru Hotel",
    slug: "mount-meru-hotel-arusha",
    status: "PUBLISHED" as const,
    type: "Standard Lodge",
    destination: "Arusha",
    description: "A well-established Arusha landmark with expansive tropical gardens and comfortable rooms, Mount Meru Hotel provides an authentic Tanzanian hospitality experience at the foot of Mount Meru. Generous grounds, a large pool, and multiple dining options create a relaxed pre-safari atmosphere just minutes from the town centre.",
    highlights: ["Tropical garden setting", "Large swimming pool", "Mount Meru backdrop", "Multiple dining venues", "Established local reputation", "Spacious grounds"],
    amenities: ["Garden rooms & suites", "Large pool", "Restaurant & bar", "Conference rooms", "Curio shop", "Free WiFi", "Tour desk", "Parking"],
    priceFrom: 160,
    coverImage: IMG.arusha(7),
    gallery: [IMG.arusha(7), IMG.arusha(12)],
    website: "",
  },
  {
    name: "Arusha Coffee Lodge",
    slug: "arusha-coffee-lodge",
    status: "PUBLISHED" as const,
    type: "Boutique Lodge",
    destination: "Arusha",
    description: "Set on a working arabica coffee estate on the outskirts of Arusha, this romantic boutique lodge delivers a uniquely Tanzanian luxury experience. Colonial-style planter's cottages are nestled among coffee plants and tropical gardens, creating an intimate atmosphere of fragrant calm between safari adventures. Evenings here — with fine dining and estate coffee — are among Tanzania's most memorable.",
    highlights: ["Working coffee plantation", "Colonial planter's cottages", "Romantic boutique atmosphere", "Estate coffee experience", "Fine dining restaurant", "Private garden cottages"],
    amenities: ["Planter's cottages", "Estate restaurant & bar", "Coffee tour & tasting", "Spa treatments", "Swimming pool", "Garden walks", "Airport transfers", "Private verandas"],
    priceFrom: 380,
    coverImage: IMG.arusha(9),
    gallery: [IMG.arusha(9), IMG.arusha(15), IMG.arusha(19)],
    website: "",
  },

  // ── Moshi / Kilimanjaro ──────────────────────────────────────────────────
  {
    name: "Kilimanjaro Wonders Hotel",
    slug: "kilimanjaro-wonders-hotel",
    status: "PUBLISHED" as const,
    type: "Standard Lodge",
    destination: "Moshi",
    description: "A comfortable and conveniently located base in Moshi, Kilimanjaro Wonders Hotel offers clean, well-appointed rooms with direct views of the snow-capped summit above. Ideal for Kilimanjaro climbers and safari travellers alike, the hotel provides reliable service, hearty meals, and a warm welcome that sets the tone for adventure.",
    highlights: ["Kilimanjaro summit views", "Moshi town centre", "Trekkers' favourite base", "Reliable local service", "Good value accommodation", "Airport proximity"],
    amenities: ["En-suite rooms", "Restaurant & bar", "Free WiFi", "Luggage storage", "Tour desk", "Airport transfers", "Gear storage", "Breakfast included"],
    priceFrom: 120,
    coverImage: IMG.kilimanjaro(3),
    gallery: [IMG.kilimanjaro(3), IMG.kilimanjaro(8)],
    website: "",
  },
  {
    name: "Parkview Inn Moshi",
    slug: "parkview-inn-moshi",
    status: "PUBLISHED" as const,
    type: "Standard Lodge",
    destination: "Moshi",
    description: "A comfortable mid-range hotel overlooking Moshi's central park with reliable service and good facilities for trekkers preparing for Kilimanjaro or returning from the summit. Simple, clean rooms and a rooftop terrace with mountain views make this a practical and pleasant base in Tanzania's climbing capital.",
    highlights: ["Central park views", "Rooftop terrace", "Kilimanjaro views on clear days", "Budget-friendly", "Close to restaurants & shops", "Trekker-friendly"],
    amenities: ["Standard rooms", "Rooftop terrace", "Restaurant", "Free WiFi", "Gear storage", "Tour desk", "Laundry service", "Secure parking"],
    priceFrom: 95,
    coverImage: IMG.kilimanjaro(5),
    gallery: [IMG.kilimanjaro(5), IMG.kilimanjaro(10)],
    website: "",
  },
  {
    name: "Weru Weru River Lodge",
    slug: "weru-weru-river-lodge",
    status: "PUBLISHED" as const,
    type: "Standard Lodge",
    destination: "Moshi",
    description: "A charming lodge set along the Weru Weru River on the slopes below Kilimanjaro, offering a peaceful garden retreat that perfectly bridges safari and mountain adventure. Lush tropical gardens, river walks, and an intimate atmosphere provide a refreshing contrast to the grandeur of the world's highest freestanding mountain towering above.",
    highlights: ["Riverside garden setting", "Kilimanjaro foothills", "Tropical garden walks", "Mountain views", "Peaceful retreat atmosphere", "River swimming"],
    amenities: ["Garden cottages", "River terrace dining", "Swimming pool", "Walking trails", "Tour planning desk", "Packed lunches for treks", "Free WiFi", "Airport transfers"],
    priceFrom: 140,
    coverImage: IMG.kilimanjaro(7),
    gallery: [IMG.kilimanjaro(7), IMG.kilimanjaro(12)],
    website: "",
  },

  // ── Lake Manyara ─────────────────────────────────────────────────────────
  {
    name: "Lake Manyara Serena Lodge",
    slug: "lake-manyara-serena-lodge",
    status: "PUBLISHED" as const,
    type: "Standard Lodge",
    destination: "Lake Manyara",
    description: "Dramatically positioned on the escarpment edge above Lake Manyara National Park, Serena Lodge commands sweeping views over the soda lake, flamingo flocks, and the Rift Valley floor stretching to the horizon. A comfortable and beautifully situated lodge offering reliable service and excellent access to one of Tanzania's most diverse and surprising wildlife habitats.",
    highlights: ["Rift Valley escarpment views", "Lake Manyara panoramas", "Tree-climbing lion country", "Flamingo flocks", "Easy circuit combination", "Swimming pool with views"],
    amenities: ["Pool with lake views", "Restaurant & bar", "Game drives", "Birdwatching walks", "Cultural excursions", "Massage on request", "Free WiFi", "Gift shop"],
    priceFrom: 280,
    coverImage: IMG.manyara(3),
    gallery: [IMG.manyara(3), IMG.manyara(7), IMG.manyara(11)],
    website: "",
  },
  {
    name: "Lake Manyara Kilimamoja Lodge",
    slug: "lake-manyara-kilimamoja-lodge",
    status: "PUBLISHED" as const,
    type: "Luxury Lodge",
    destination: "Lake Manyara",
    description: "An intimate luxury lodge perched on the Rift Valley escarpment with extraordinary views over Lake Manyara. Sophisticated rooms and suites harmonize with the natural landscape, while a serene infinity pool, fine dining and expert guided activities deliver a premium Northern Circuit experience. The combination of lake, escarpment and forest habitats makes Manyara one of Tanzania's most biodiverse parks.",
    highlights: ["Infinity pool with lake views", "Rift Valley escarpment luxury", "Tree-climbing lions & elephants", "Diverse habitats & birding", "Expert lodge guides", "Couples & romantic escapes"],
    amenities: ["Luxury suites", "Infinity pool", "Fine dining", "Spa", "Walking safaris", "Night drives", "Cultural excursions", "Private verandas"],
    priceFrom: 520,
    coverImage: IMG.manyara(5),
    gallery: [IMG.manyara(5), IMG.manyara(9), IMG.manyara(13)],
    website: "",
  },
  {
    name: "Escarpment Luxury Lodge",
    slug: "escarpment-luxury-lodge-manyara",
    status: "PUBLISHED" as const,
    type: "Luxury Lodge",
    destination: "Lake Manyara",
    description: "Clinging to the dramatic edge of the Great Rift Valley escarpment, Escarpment Luxury Lodge delivers some of Tanzania's most breathtaking views. Floor-to-ceiling glass walls, private plunge pools and a design that embraces the sheer drama of the landscape create an experience that is as visually stunning as the wildlife below. The ultimate luxury stopover on a Northern Circuit safari.",
    highlights: ["Glass-walled suites with escarpment views", "Private plunge pools", "Dramatic Rift Valley architecture", "Lake Manyara vista", "Sunset cocktail terrace", "Photography paradise"],
    amenities: ["Suites with plunge pools", "Glass-wall panoramic lounge", "Fine dining", "Sunset cocktail deck", "Spa & massage", "Game drives", "Cultural visits", "Helipad"],
    priceFrom: 650,
    coverImage: IMG.manyara(7),
    gallery: [IMG.manyara(7), IMG.manyara(11)],
    website: "",
  },

  // ── Ndutu / Southern Serengeti ───────────────────────────────────────────
  {
    name: "Ndutu Safari Lodge",
    slug: "ndutu-safari-lodge",
    status: "PUBLISHED" as const,
    type: "Standard Lodge",
    destination: "Ndutu, Southern Serengeti",
    description: "The original and beloved lodge in Ndutu, established for decades as the classic base for calving season safaris in the southern Serengeti. Simple, comfortable accommodation in the heart of the action, surrounded by woodland, soda lakes and the greatest concentration of predators and prey in East Africa during the January to March season.",
    highlights: ["Classic calving season lodge", "Original Ndutu institution", "Woodland & lake setting", "Predator concentration", "Accessible mid-range option", "Decades of heritage"],
    amenities: ["Lodge rooms", "Restaurant & bar", "Communal lounge", "Game drives", "Walking safaris", "Airport transfers", "Full board", "Local guide network"],
    priceFrom: 320,
    coverImage: IMG.migration(1),
    gallery: [IMG.migration(1), IMG.migration(5)],
    website: "",
  },

  // ── Central Serengeti ────────────────────────────────────────────────────
  {
    name: "Four Seasons Safari Lodge Serengeti",
    slug: "four-seasons-safari-lodge-serengeti",
    status: "PUBLISHED" as const,
    type: "Luxury Lodge",
    destination: "Central Serengeti",
    description: "The Serengeti's most architecturally striking lodge, Four Seasons Safari Lodge sits above a natural waterhole that draws wildlife day and night. Infinity pools with big game drinking metres away, a world-class spa, and the signature Four Seasons level of personalised service deliver an ultra-luxury safari experience that redefines comfort in the wilderness.",
    highlights: ["Natural waterhole at lodge", "Infinity pool with wildlife views", "World-class spa & wellness", "Ultra-luxury rooms & suites", "Night wildlife viewing from lodge", "Four Seasons service level"],
    amenities: ["Luxury suites & villas", "Multiple swimming pools", "Full spa", "Multiple restaurants", "Waterhole hide", "Game drives", "Guided walks", "Children's programme"],
    priceFrom: 1500,
    coverImage: IMG.serengeti(10),
    gallery: [IMG.serengeti(10), IMG.serengeti(18), IMG.serengeti(28)],
    website: "",
  },
  {
    name: "Meliá Serengeti Lodge",
    slug: "melia-serengeti-lodge",
    status: "PUBLISHED" as const,
    type: "Luxury Lodge",
    destination: "Central Serengeti",
    description: "A design-forward luxury lodge in the central Serengeti, Meliá delivers a contemporary interpretation of safari luxury with spacious villas, private plunge pools and a striking infinity pool that seems to pour into the savannah. Modern interiors, curated cuisine and expert-guided game drives make this one of the Serengeti's most stylish addresses.",
    highlights: ["Contemporary luxury design", "Villa-style accommodations", "Infinity pool", "Central Serengeti access", "Signature restaurant", "Full game circuit"],
    amenities: ["Luxury villas with pools", "Infinity pool", "Fine dining restaurant", "Spa & gym", "Expert guides", "Night drives", "Balloon safaris nearby", "Helicopter excursions"],
    priceFrom: 900,
    coverImage: IMG.serengeti(14),
    gallery: [IMG.serengeti(14), IMG.serengeti(22), IMG.serengeti(33)],
    website: "",
  },
  {
    name: "Serengeti Serena Lodge",
    slug: "serengeti-serena-lodge",
    status: "PUBLISHED" as const,
    type: "Standard Lodge",
    destination: "Central Serengeti",
    description: "An enduring favourite with deep roots in the Serengeti experience, Serena Lodge sits atop a forested hill in the heart of the park with sweeping views over golden plains. Its circular rondavel architecture, intimate atmosphere and reliable Serena service make it a trusted choice for families and safari first-timers seeking comfort, value and year-round game viewing.",
    highlights: ["Hilltop position & views", "Circular rondavel design", "Family-friendly atmosphere", "Year-round game viewing", "Reliable Serena hospitality", "Swimming pool"],
    amenities: ["Circular rondavel rooms", "Swimming pool", "Restaurant & bar", "Gift shop", "Game drives", "Cultural village visits", "Free WiFi", "Laundry service"],
    priceFrom: 350,
    coverImage: IMG.serengeti(20),
    gallery: [IMG.serengeti(20), IMG.serengeti(28), IMG.serengeti(38)],
    website: "",
  },

  // ── Ngorongoro / Crater ──────────────────────────────────────────────────
  {
    name: "Ngorongoro Crater Lodge",
    slug: "ngorongoro-crater-lodge",
    status: "PUBLISHED" as const,
    type: "Luxury Lodge",
    destination: "Ngorongoro Crater",
    description: "Perched on the rim of the world's largest intact volcanic caldera, Ngorongoro Crater Lodge stands as one of Africa's most iconic and extravagant lodges. Three separate camps of thatched-roof suites dangle over the 600-metre crater walls, combining Maasai influences with European baroque interiors for a safari experience that is deliberately, gloriously theatrical.",
    highlights: ["Crater rim iconic position", "Africa's most dramatic lodge", "Three separate camps", "European baroque interiors", "Butler service per suite", "Big Five crater descents"],
    amenities: ["Baronial suites", "Private butlers", "Open fire lounges", "Fine dining", "Wine cellar", "Crater game drives", "Maasai cultural experiences", "Helicopter excursions"],
    priceFrom: 1800,
    coverImage: IMG.ngorongoro(5),
    gallery: [IMG.ngorongoro(5), IMG.ngorongoro(9), IMG.ngorongoro(1)],
    website: "",
  },
  {
    name: "Ngorongoro Serena Lodge",
    slug: "ngorongoro-serena-lodge",
    status: "PUBLISHED" as const,
    type: "Standard Lodge",
    destination: "Ngorongoro Crater",
    description: "Blending harmoniously into the crater rim forest, Ngorongoro Serena Lodge offers comfortable and reliable accommodation with memorable crater views. Built from local stone and wood with a design that mirrors the rocky outcrops and indigenous trees, the lodge provides a warm and welcoming base for daily crater descents in search of the legendary black rhino and Big Five.",
    highlights: ["Forest rim integration", "Crater panoramic views", "Local stone & timber design", "Black rhino crater access", "Reliable Serena service", "Warm family atmosphere"],
    amenities: ["Stone & timber rooms", "Restaurant & bar", "Swimming pool", "Gift shop", "Game drives", "Guided walks", "Free WiFi", "Full board included"],
    priceFrom: 320,
    coverImage: IMG.ngorongoro(7),
    gallery: [IMG.ngorongoro(7), IMG.ngorongoro(3)],
    website: "",
  },
  {
    name: "Ngorongoro Sopa Lodge",
    slug: "ngorongoro-sopa-lodge",
    status: "PUBLISHED" as const,
    type: "Standard Lodge",
    destination: "Ngorongoro Crater",
    description: "A large and comfortable lodge on the eastern rim of Ngorongoro Crater offering reliable service and straightforward access to daily crater game drives. Spacious rooms, a swimming pool and friendly staff make this a popular choice for group safaris and families seeking solid, value-oriented accommodation on the Northern Circuit.",
    highlights: ["Eastern crater rim position", "Large group capacity", "Swimming pool", "Value for money", "Daily crater descents", "Family-friendly"],
    amenities: ["Spacious rooms", "Large swimming pool", "Restaurant & bar", "Conference room", "Gift shop", "Game drives", "Free WiFi", "Full board"],
    priceFrom: 240,
    coverImage: IMG.ngorongoro(9),
    gallery: [IMG.ngorongoro(9), IMG.ngorongoro(5)],
    website: "",
  },
  {
    name: "Rhino Lodge Ngorongoro",
    slug: "rhino-lodge-ngorongoro",
    status: "PUBLISHED" as const,
    type: "Standard Lodge",
    destination: "Ngorongoro Crater",
    description: "The most accessible and budget-friendly option on the Ngorongoro Crater rim, Rhino Lodge provides simple, clean rooms and an intimate atmosphere with genuine Tanzanian warmth. A favourite among independent travellers and budget-conscious safari-goers who wish to experience the wonder of the crater without compromising on the essential magic of waking up above the world's greatest caldera.",
    highlights: ["Budget-friendly crater rim", "Clean & comfortable", "Genuine local warmth", "Good crater views", "Independent traveller favourite", "Simple authentic experience"],
    amenities: ["Simple en-suite rooms", "Restaurant & bar", "Basic facilities", "Game drives available", "Free WiFi", "Packed lunches", "Airport transfers", "Full board"],
    priceFrom: 120,
    coverImage: IMG.ngorongoro(11),
    gallery: [IMG.ngorongoro(11), IMG.ngorongoro(7)],
    website: "",
  },

  // ── Karatu ───────────────────────────────────────────────────────────────
  {
    name: "Ngorongoro Farm House",
    slug: "ngorongoro-farm-house",
    status: "PUBLISHED" as const,
    type: "Boutique Lodge",
    destination: "Karatu",
    description: "Set on a working coffee and wheat farm in the fertile highlands of Karatu, Ngorongoro Farm House is a charming boutique retreat between Tarangire and Ngorongoro. Stone cottages scattered through gardens produce a feeling of staying at a family estate, while organic farm meals, coffee tours and the green highland landscape provide a restorative contrast to the open plains.",
    highlights: ["Working farm & coffee estate", "Stone cottage style", "Organic farm cuisine", "Karatu highland setting", "Garden & orchard walks", "Authentic homestead atmosphere"],
    amenities: ["Farm cottages", "Restaurant with farm produce", "Swimming pool", "Coffee farm tour", "Mountain biking", "Cultural village visits", "Free WiFi", "Airport transfers"],
    priceFrom: 220,
    coverImage: IMG.ngorongoro(1),
    gallery: [IMG.ngorongoro(1), IMG.arusha(6)],
    website: "",
  },
  {
    name: "Bougainvillea Safari Lodge",
    slug: "bougainvillea-safari-lodge-karatu",
    status: "PUBLISHED" as const,
    type: "Standard Lodge",
    destination: "Karatu",
    description: "A comfortable and colourful lodge in Karatu's highland gardens, Bougainvillea offers a pleasant and practical base between the Northern Circuit parks. Its namesake flowering plants cascade across the property in vivid colour, creating a garden atmosphere that is a welcome contrast to the wide-open game plains.",
    highlights: ["Colourful garden setting", "Comfortable highland location", "Good Northern Circuit access", "Swimming pool", "Friendly family service", "Value mid-range option"],
    amenities: ["Garden rooms", "Swimming pool", "Restaurant & bar", "Free WiFi", "Tour desk", "Airport transfers", "Laundry service", "Full board"],
    priceFrom: 160,
    coverImage: IMG.ngorongoro(3),
    gallery: [IMG.ngorongoro(3), IMG.arusha(11)],
    website: "",
  },
  {
    name: "Marera Valley Lodge",
    slug: "marera-valley-lodge-karatu",
    status: "PUBLISHED" as const,
    type: "Standard Lodge",
    destination: "Karatu",
    description: "Positioned in the scenic Marera Valley between Manyara and Ngorongoro, this lodge offers comfortable rooms and beautiful highland scenery as a restful overnight between safari days. The valley's fertile landscape and cultural richness add a dimension beyond game viewing, with local walks, village visits and a warm sense of Tanzanian welcome.",
    highlights: ["Marera Valley views", "Between Manyara & Ngorongoro", "Highland scenery", "Cultural village walks", "Peaceful atmosphere", "Good value"],
    amenities: ["Valley view rooms", "Restaurant & bar", "Swimming pool", "Cultural walks", "Tour planning", "Free WiFi", "Airport transfers", "Full board"],
    priceFrom: 145,
    coverImage: IMG.manyara(9),
    gallery: [IMG.manyara(9), IMG.ngorongoro(3)],
    website: "",
  },

  // ── Tarangire ────────────────────────────────────────────────────────────
  {
    name: "Tarangire Sopa Lodge",
    slug: "tarangire-sopa-lodge",
    status: "PUBLISHED" as const,
    type: "Standard Lodge",
    destination: "Tarangire National Park",
    description: "A reliable and comfortable lodge set inside Tarangire National Park with direct access to one of Tanzania's most underrated wildlife destinations. Famous for its elephant population — the largest seasonal concentration in Africa — and ancient baobab landscapes, Tarangire offers a compelling alternative to the busier Northern Circuit parks.",
    highlights: ["Inside park boundaries", "Tarangire elephant herds", "Baobab landscape setting", "Year-round game viewing", "Reliable Sopa service", "Family-friendly"],
    amenities: ["Lodge rooms", "Swimming pool", "Restaurant & bar", "Game drives", "Walking safaris", "Gift shop", "Free WiFi", "Full board"],
    priceFrom: 240,
    coverImage: IMG.tarangire(8),
    gallery: [IMG.tarangire(8), IMG.tarangire(14), IMG.tarangire(20)],
    website: "",
  },
  {
    name: "Tarangire Treetops",
    slug: "tarangire-treetops-lodge",
    status: "PUBLISHED" as const,
    type: "Luxury Lodge",
    destination: "Tarangire National Park",
    description: "Among Tanzania's most distinctive accommodations, Tarangire Treetops builds its extraordinary suites into and around ancient baobab and marula trees. Treehouse-style rooms sit elevated among the canopy, with star beds for sleeping under the Milky Way, platforms suspended above the bush and a sense of childlike wonder combined with five-star luxury.",
    highlights: ["Tree house suite architecture", "Star beds under the stars", "Ancient baobab integration", "Elevated canopy access", "Intimate 20-suite capacity", "Unique unforgettable design"],
    amenities: ["Treehouse suites", "Star bed decks", "Swimming pool", "Lounge & bar", "Fine dining", "Walking safaris", "Night drives", "Bush spa treatments"],
    priceFrom: 750,
    coverImage: IMG.tarangire(3),
    gallery: [IMG.tarangire(3), IMG.tarangire(10), IMG.tarangire(17)],
    website: "",
  },
  {
    name: "Chem Chem Lodge",
    slug: "chem-chem-lodge-tarangire",
    status: "PUBLISHED" as const,
    type: "Luxury Lodge",
    destination: "Tarangire",
    description: "A private and exclusive luxury lodge on a concession bordering Tarangire National Park, Chem Chem offers an intimate safari experience available only to its handful of guests. Chic East African colonial design, a private conservancy accessed only by lodge guests, and a conservation ethos that extends from landscape restoration to community employment set this property apart.",
    highlights: ["Private concession bordering Tarangire", "Exclusive to lodge guests only", "East African colonial design", "Conservation & community led", "Exceptional guiding team", "Highly personalised service"],
    amenities: ["Colonial luxury tents", "Private pool", "Gourmet dining", "Horse riding", "Walking safaris", "Conservation treks", "Spa treatments", "Sundowner flights"],
    priceFrom: 1200,
    coverImage: IMG.tarangire(6),
    gallery: [IMG.tarangire(6), IMG.tarangire(13), IMG.tarangire(21)],
    website: "",
  },

  // ── Arusha National Park ─────────────────────────────────────────────────
  {
    name: "Hatari Lodge",
    slug: "hatari-lodge-arusha-np",
    status: "PUBLISHED" as const,
    type: "Boutique Lodge",
    destination: "Arusha National Park",
    description: "Named after the 1962 John Wayne film shot on these very grounds, Hatari Lodge is one of Tanzania's most characterful properties. Set on the edge of Arusha National Park with views to both Mount Meru and Kilimanjaro, this intimate farmhouse lodge blends cinematic history, black rhino conservancy work and Mt. Meru canoe safaris into a uniquely memorable experience.",
    highlights: ["John Wayne film heritage", "Mount Meru & Kilimanjaro views", "Rhino conservation sanctuary", "Canoe safaris on crater lake", "Intimate farmhouse atmosphere", "Unique cultural history"],
    amenities: ["Farmhouse rooms", "Garden & pool", "Restaurant & bar", "Canoe safaris", "Mt. Meru walks", "Rhino tracking", "Cultural history tours", "Airport transfers"],
    priceFrom: 450,
    coverImage: IMG.arusha(14),
    gallery: [IMG.arusha(14), IMG.arusha(18), IMG.kilimanjaro(1)],
    website: "",
  },
  {
    name: "Ngare Sero Mountain Lodge",
    slug: "ngare-sero-mountain-lodge",
    status: "PUBLISHED" as const,
    type: "Standard Lodge",
    destination: "Arusha National Park",
    description: "A tranquil and historic property on the forest edge of Arusha National Park, Ngare Sero Mountain Lodge sits beside a spring-fed lake visited by flamingos and prolific birdlife. Built on a former German colonial farm, the lodge's mature gardens, spring swimming and relaxed pace make it a favourite for those seeking peaceful beauty between safari adventures.",
    highlights: ["Spring-fed lake swimming", "Colonial farm heritage", "Flamingo & bird viewing", "Forest edge location", "Tranquil garden atmosphere", "Historic German colonial buildings"],
    amenities: ["Farmhouse rooms", "Natural spring pool", "Restaurant & bar", "Birdwatching walks", "Cultural heritage tours", "Canoe trips", "Free WiFi", "Airport transfers"],
    priceFrom: 280,
    coverImage: IMG.arusha(16),
    gallery: [IMG.arusha(16), IMG.arusha(20)],
    website: "",
  },

  // ── Sayari Private Villa ─────────────────────────────────────────────────
  {
    name: "Sayari Retreats",
    slug: "sayari-retreats",
    status: "PUBLISHED" as const,
    type: "Luxury Lodge",
    destination: "Northern Serengeti",
    description: "The ultimate expression of Serengeti luxury, Sayari Retreats delivers elevated exclusivity with private plunge pools, private guides and dedicated chefs for each guest group. Complete privacy, flexible dining and lounging spaces, and direct access to the most dramatic wildlife theatre in the northern Serengeti make this the destination for those who want the Serengeti entirely on their own terms.",
    highlights: ["Complete private exclusivity", "Private guide & dedicated chef", "Private plunge pools", "Flexible private dining", "Northern Serengeti prime position", "Fully bespoke experience"],
    amenities: ["Private villa suites", "Private plunge pools", "Dedicated chef", "Private guide", "Private vehicle", "Bespoke game drives", "Private dining anywhere", "Airport transfers"],
    priceFrom: 2200,
    coverImage: IMG.serengeti(3),
    gallery: [IMG.serengeti(3), IMG.serengeti(11), IMG.serengeti(19)],
    website: "",
  },
]

async function upsert(model: "lodge" | "camp", data: typeof LODGES[0]) {
  const repo = model === "lodge" ? prisma.lodge : prisma.camp
  const existing = await (repo as typeof prisma.lodge).findUnique({ where: { slug: data.slug } })
  if (existing) {
    await (repo as typeof prisma.lodge).update({ where: { slug: data.slug }, data })
    console.log(`  ✓ Updated ${model}: ${data.name}`)
  } else {
    await (repo as typeof prisma.lodge).create({ data })
    console.log(`  ✓ Created ${model}: ${data.name}`)
  }
}

async function main() {
  console.log("Seeding lodges...")
  for (const l of LODGES) await upsert("lodge", l as typeof LODGES[0])

  console.log("\nSeeding camps...")
  for (const c of CAMPS) await upsert("camp", c as typeof CAMPS[0])

  const lodgeCount = await prisma.lodge.count()
  const campCount = await prisma.camp.count()
  console.log(`\n✅ Done! Database now has ${lodgeCount} lodges and ${campCount} camps.`)
}

main().catch(console.error).finally(() => prisma.$disconnect())
